quanta.pdc/quanta.pdc/Controllers/WorkController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.IO.Compression;
using System.Linq;
using System.Threading.Tasks;
using cns.Data;
using cns.Models;
using cns.Services;
using cns.Services.App;
using cns.Services.Enum;
using cns.Services.Helper;
using cns.ViewModels;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using NPOI.SS.UserModel;
using NPOI.XSSF.UserModel;

namespace cns.Controllers
{
    public class WorkController : Controller
    {
        private readonly ApplicationDbContext _context;

        private readonly IHostingEnvironment _hostingEnvironment;

        public WorkController(IHostingEnvironment hostingEnvironment, ApplicationDbContext context, UserManager<IdentityUser> userManager)
        {
            _hostingEnvironment = hostingEnvironment;
            _context = context;
        }

        [HttpGet]
        [ActionCheck]
        public IActionResult Assign()
        {
            //讀取使用者資訊
            CurrentUser UserInfo = HttpContext.Session.GetObjectFromJson<CurrentUser>(SessionKey.usrInfo);

            AuthenticationService authenticationService = new AuthenticationService(_context);
            ParameterService parameterService = new ParameterService(_context, UserInfo.User);
            PrivilegeService privilegeService = new PrivilegeService(_context, UserInfo.User);
            WorkService WorkService = new WorkService(_context, UserInfo.User);
            m_AssignPartial model = new m_AssignPartial();

            model.MemberID = UserInfo.User.MemberID.ToString();
            model.PrivilegeList = privilegeService.GetPrivilegeList(UserInfo.User.MemberID);
            model.m_FormStage = FormEnum.GetAssign_Form_StageDic();
            //model.m_ProcessorList = authenticationService.GetAccountList(MemberEnum.Role.PDC_Processor).Select(x => new Microsoft.AspNetCore.Mvc.Rendering.SelectListItem() { Text = x.UserEngName + "(" + x.UserName + ")", Value = x.MemberID.ToString() }).ToList();
            model.m_ProcessorList = privilegeService.GetProcessorList();
            model.m_CompCodeList = parameterService.GetParameterList(ParameterKey.ConfigurationCompCode).Select(x => new Microsoft.AspNetCore.Mvc.Rendering.SelectListItem() { Text = x.ParameterText, Value = x.ParameterText }).ToList();
            model.m_DeptCodeList = authenticationService.GetDepartmentList().GroupBy(x => new { x.BUCode, x.ShowName }).Distinct().Select(x => new Microsoft.AspNetCore.Mvc.Rendering.SelectListItem() { Text = x.Key.ShowName, Value = x.Key.BUCode }).ToList();

            List<PDC_Parameter> data = parameterService.GetParameterList(ParameterKey.PCBTypeList);
            model.PCBTypeList = parameterService.GetSelectList(data.Where(x => x.ParameterValue == "PCBType").FirstOrDefault().ParameterID);
            model.PCBLayoutStatusList = parameterService.GetSelectList(data.Where(x => x.ParameterValue == "PCBLayoutStatus").FirstOrDefault().ParameterID);

            bool? IsMB = null;
            if (model.PrivilegeList.Where(x => x.RoleID == MemberEnum.Role.PDC_Designator).Any())
                IsMB = model.PrivilegeList.Where(x => x.RoleID == MemberEnum.Role.PDC_Designator).FirstOrDefault().IsMB;

            model.vw_FormQueryList = WorkService.GetFilterFormList(new QueryParam() { FormStage = FormEnum.Form_Stage.Apply,IsMB = IsMB });
            return View(model);
        }

        [HttpPost]
        [ActionCheck]
        public IActionResult Assign(m_AssignPartial model)
        {
            //讀取使用者資訊
            CurrentUser UserInfo = HttpContext.Session.GetObjectFromJson<CurrentUser>(SessionKey.usrInfo);

            AuthenticationService authenticationService = new AuthenticationService(_context);
            ParameterService parameterService = new ParameterService(_context, UserInfo.User);
            PrivilegeService privilegeService = new PrivilegeService(_context, UserInfo.User);
            WorkService WorkService = new WorkService(_context, UserInfo.User);

            model.MemberID = UserInfo.User.MemberID.ToString();
            model.PrivilegeList = privilegeService.GetPrivilegeList(UserInfo.User.MemberID);
            model.m_FormStage = FormEnum.GetAssign_Form_StageDic();
            model.m_ProcessorList = privilegeService.GetProcessorList();
            model.m_CompCodeList = parameterService.GetParameterList(ParameterKey.ConfigurationCompCode).Select(x => new Microsoft.AspNetCore.Mvc.Rendering.SelectListItem() { Text = x.ParameterText, Value = x.ParameterText }).ToList();
            model.m_DeptCodeList = authenticationService.GetDepartmentList().GroupBy(x => new { x.BUCode, x.ShowName }).Distinct().Select(x => new Microsoft.AspNetCore.Mvc.Rendering.SelectListItem() { Text = x.Key.ShowName, Value = x.Key.BUCode }).ToList();

            List<PDC_Parameter> data = parameterService.GetParameterList(ParameterKey.PCBTypeList);
            model.PCBTypeList = parameterService.GetSelectList(data.Where(x => x.ParameterValue == "PCBType").FirstOrDefault().ParameterID);
            model.PCBLayoutStatusList = parameterService.GetSelectList(data.Where(x => x.ParameterValue == "PCBLayoutStatus").FirstOrDefault().ParameterID);

            model.vw_FormQueryList = WorkService.GetFilterFormList(model.QueryParam);

            return View(model);
        }

        [HttpGet]
        [ActionCheck]
        public IActionResult WorkArea()
        {
            //讀取使用者資訊
            CurrentUser UserInfo = HttpContext.Session.GetObjectFromJson<CurrentUser>(SessionKey.usrInfo);

            AuthenticationService authenticationService = new AuthenticationService(_context);
            ParameterService parameterService = new ParameterService(_context, UserInfo.User);
            WorkService WorkService = new WorkService(_context, UserInfo.User);
            PrivilegeService privilegeService = new PrivilegeService(_context, UserInfo.User);
            m_WorkAreaPartial model = new m_WorkAreaPartial();

            model.m_FormStage = FormEnum.GetWorkArea_Form_StageDic();
            model.QueryParam.PDC_Member = UserInfo.User.MemberID.ToString();
            model.QueryParam.CreatorName = UserInfo.User.UserEngName + "(" + UserInfo.User.UserName + ")";
            model.QueryParam.Form_Status = FormEnum.Form_Status.Work;
            model.m_ProcessorList = privilegeService.GetProcessorList();
            model.IsAdmin = UserInfo.PrivilegeList.Where(x => x.RoleID == MemberEnum.Role.PDC_Administrator).Any();

            model.vw_FormQueryList = WorkService.GetFilterWorkFormList(model.QueryParam);

            return View(model);
        }

        [HttpPost]
        [ActionCheck]
        public IActionResult WorkArea(m_WorkAreaPartial model)
        {
            //讀取使用者資訊
            CurrentUser UserInfo = HttpContext.Session.GetObjectFromJson<CurrentUser>(SessionKey.usrInfo);

            AuthenticationService authenticationService = new AuthenticationService(_context);
            ParameterService parameterService = new ParameterService(_context, UserInfo.User);
            PrivilegeService privilegeService = new PrivilegeService(_context, UserInfo.User);
            WorkService WorkService = new WorkService(_context, UserInfo.User);

            model.m_FormStage = FormEnum.GetWorkArea_Form_StageDic();
            if(string.IsNullOrWhiteSpace(model.QueryParam.PDC_Member))
                model.QueryParam.PDC_Member = UserInfo.User.MemberID.ToString();

            model.QueryParam.CreatorName = UserInfo.User.UserEngName + "(" + UserInfo.User.UserName + ")";
            model.m_ProcessorList = privilegeService.GetProcessorList();
            model.IsAdmin = UserInfo.PrivilegeList.Where(x => x.RoleID == MemberEnum.Role.PDC_Administrator).Any();

            model.vw_FormQueryList = WorkService.GetFilterWorkFormList(model.QueryParam);

            return View(model);
        }

        [ActionCheck]
        public IActionResult WorkDetail(string AppliedFormNo)
        {
            //讀取使用者資訊
            CurrentUser UserInfo = HttpContext.Session.GetObjectFromJson<CurrentUser>(SessionKey.usrInfo);

            FormService formService = new FormService(_hostingEnvironment, _context, UserInfo.User);
            FileService fileService = new FileService(_hostingEnvironment, _context, UserInfo.User);
            ExcelHepler excelHepler = new ExcelHepler(_hostingEnvironment);
            ParameterService parameterService = new ParameterService(_context, UserInfo.User);

            PDC_Form Form = formService.GetFormOne(AppliedFormNo);

            m_WorkDetailPartial model = new m_WorkDetailPartial();

            model.vw_FormQuery = formService.GetFilterFormList(new QueryParam() { AppliedFormNo = AppliedFormNo }).FirstOrDefault();
            model.m_PDC_Form = Form;

            List<PDC_Parameter> data = parameterService.GetParameterList(ParameterKey.PCBTypeList);
            model.PCBTypeList = parameterService.GetSelectList(data.Where(x => x.ParameterValue == "PCBType").FirstOrDefault().ParameterID);
            model.PCBLayoutStatusList = parameterService.GetSelectList(data.Where(x => x.ParameterValue == "PCBLayoutStatus").FirstOrDefault().ParameterID);
            model.ReleaseResultList = parameterService.GetParameterList(data.Where(x => x.ParameterValue == "ReleaseResult").FirstOrDefault().ParameterID);
            model.RejectResultList = parameterService.GetParameterList(data.Where(x => x.ParameterValue == "RejectResult").FirstOrDefault().ParameterID);

            model.m_ReleaseWorkHour = parameterService.GetParameterOne(ParameterKey.ConfigurationRelease);
            model.m_RejectWorkHour = parameterService.GetParameterOne(ParameterKey.ConfigurationReject);
            model.Member = UserInfo.User;

            model.m_ConfigurationWorkDetail = parameterService.GetParameterOne(ParameterKey.ConfigurationWorkDetail);

quanta.pdc/quanta.pdc/Views/Work/WorkArea.cshtml
@model m_WorkAreaPartial
@{
    ViewData["Title"] = "Work 工作區";
}

<div class="page-content">
    <div class="page-info container">
        <div class="row">
            <div class="col">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="#">PDC - CNS平台</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Work 工作區</li>
                    </ol>
                </nav>
            </div>
        </div>
        
    </div>
    <div class="main-wrapper container">
        <div class="row">
            <div class="col-lg-12">
                <form asp-action="WorkArea" method="post" enctype="multipart/form-data">
                    <div class="card">
                        <div class="card-body">
                            <p class="card-title">查詢條件</p>
                            <div class="row">
                                <div class="col-md-3">
                                    <div class="form-group">
                                        <label>負責人</label>
                                        @if (Model.IsAdmin)
                                        {
                                            <select class="select2 form-control" id="PDC_Member" asp-for="QueryParam.PDC_Member">
                                                <option value=""></option>
                                                @foreach (var item in Model.m_ProcessorList)
                                                {
                                                    <option value="@item.Value">@item.Text</option>
                                                }
                                            </select>
                                        }
                                        else
                                        {
                                            <input type="text" class="form-control" id="Member" asp-for="QueryParam.CreatorName" disabled="disabled">
                                        }
                                    </div>
                                </div>
                                <div class="col-md-3">
                                    <div class="form-group">
                                        <label>處理結果</label>
                                        @*<input type="email" class="form-control" placeholder="未處理/Released/Rejected/已抽單" disabled="disabled">*@
                                        <select class="select2 form-control" id="FormStage" asp-for="QueryParam.Form_Status">
                                            <option value=""></option>
                                            @foreach (var item in Model.m_FormStage)
                                            {
                                                <option value="@item.Key">@item.Value</option>
                                            }
                                        </select>
                                    </div>
                                </div>
                                <div class="col-md-2">
                                    <div class="form-group">
                                        <label>查詢日期</label>
                                        <input type="text" class="form-control" id="SearchDate_Start" asp-for="QueryParam.SearchDate_Start">
                                    </div>

                                </div>
                                <div class="col-md-2">
                                    <div class="form-group">
                                        <label>　<a></a></label>
                                        <input type="text" class="form-control" id="SearchDate_End" asp-for="QueryParam.SearchDate_End">
                                    </div>

                                </div>
                                <div class="col-md-2">
                                    <div class="form-group">
                                        <label>申請單號</label>
                                        <input type="text" class="form-control" id="AppliedFormNo" asp-for="QueryParam.AppliedFormNo">
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-4">
                                    <div style="padding-top: 10px;">
                                        <button type="submit" class="btn btn-outline-info" id="SearchApply" style=" padding: 4px 25px;">查詢紀錄</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
        @if (Model.vw_FormQueryList != null)
        {
            <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-body" style="padding-bottom: 0px;">
                            <p class="card-title">查詢結果</p>
                            <div class="table-responsive">
                                <table class="table table-hover">
                                    <thead class="thead-dark">
                                        <tr>
                                            <th scope="col" style="">
                                                申請單號
                                            </th>
                                            <th scope="col" style="">單號順序</th>
                                            <th scope="col" style="">申請狀態</th>
                                            <th scope="col" style="">申請日期</th>
                                            <th scope="col" style="">公司別</th>
                                            <th scope="col" style="">部門</th>
                                            <th scope="col" style="">
                                                PCB Layout<br>Status
                                            </th>
                                            <th scope="col" style="">Project</th>
                                            <th scope="col" style="">Board Type</th>
                                            <th scope="col" style="">Rev.</th>
                                            <th scope="col" style="">指派意見</th>
                                            <th scope="col" style="">PDC 負責人</th>
                                            <th scope="col" style="">處理結果</th>
                                            <th scope="col" style="">完成日期</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @if (Model.vw_FormQueryList.Count == 0)
                                        {
                                            <tr>
                                                <td colspan="14" style="font-weight:bold;font-size:larger">查無資料</td>
                                            </tr>
                                        }
                                        else
                                        {
                                            for (int i = 0; i <= Model.vw_FormQueryList.Count - 1; i++)
                                            {
                                                var Path = Url.Action("WorkDetail", "Work") + "/?AppliedFormNo=" + @Model.vw_FormQueryList[i].AppliedFormNo;
                                    <tr>
                                        <td style="text-align:left">
                                            <a href="@Path" class="btn btn-outline-light" style=" padding: 4px 10px;" id="mail-compose">@Model.vw_FormQueryList[i].AppliedFormNo</a>
                                        </td>
                                        <td>@Model.vw_FormQueryList[i].ApplyOrder</td>
                                        <td>@Model.vw_FormQueryList[i].FormStatus</td>
                                        @if (Model.vw_FormQueryList[i].FormStatusCode == cns.Services.Enum.FormEnum.Form_Status.NoApply || Model.vw_FormQueryList[i].FormStatusCode == cns.Services.Enum.FormEnum.Form_Status.Reject)
                                        {
                                            <td></td>
                                        }
                                        else
                                        {
                                            <td>
                                                @if (Model.vw_FormQueryList[i].ApplyDate.Year != 1)
                                                {
                                                    @Model.vw_FormQueryList[i].ApplyDate.ToString("yyyy/MM/dd")<br>
                                                    @Model.vw_FormQueryList[i].ApplyDate.ToString("HH:mm:ss")
                                                }
                                            </td>
                                        }
                                        <td>@Model.vw_FormQueryList[i].CompCode</td>
                                        <td>@Model.vw_FormQueryList[i].BUName</td>
                                        <td>@Model.vw_FormQueryList[i].PCBTypeStatusName</td>
                                        <td>@Model.vw_FormQueryList[i].ProjectName</td>
                                        <td>@Model.vw_FormQueryList[i].BoardTypeName</td>
                                        <td>@Model.vw_FormQueryList[i].Revision</td>
                                        <td>@Model.vw_FormQueryList[i].Result</td>
                                        <td>
                                            @Html.Raw(Model.vw_FormQueryList[i].PDC_MemberName)
                                        </td>

                                        @if (Model.vw_FormQueryList[i].FormStatusCode == cns.Services.Enum.FormEnum.Form_Status.Release)
                                        {
                                            <td>@Model.vw_FormQueryList[i].StageName</td>
                                            <td>
                                                @(Model.vw_FormQueryList[i].StageDate.HasValue ? Model.vw_FormQueryList[i].StageDate.Value.ToString("yyyy/MM/dd") : "")
                                                <br />
                                                @(Model.vw_FormQueryList[i].StageDate.HasValue ? Model.vw_FormQueryList[i].StageDate.Value.ToString("HH:mm:ss") : "")
                                            </td>
                                        }
                                        else
                                        {
                                            <td></td>
                                            <td></td>
                                        }
                                    </tr>
                                            }
                                        }
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        }
        <!-- End of Main -->
    </div>

</div>

@section Styles{
    <!-- data tables css -->
    <link rel="stylesheet" href="~/assets/plugins/data-tables/css/datatables.min.css">
    <style>
        input[type="text"]:disabled {
            background: gray;
        }

        input[type="radio"]:disabled {
            background: gray;
        }

        select:disabled {
            background: gray;
        }
    </style>
}

@section Scripts {
    <!-- datatable Js -->
    <script src="~/assets/plugins/data-tables/js/datatables.min.js"></script>
    <script src="~/assets/js/pages/tbl-datatable-custom.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $('#SearchDate_Start').datepicker({ dateFormat: 'yy-mm-dd' });
            $('#SearchDate_End').datepicker({ dateFormat: 'yy-mm-dd' });
        });

    </script>
}